# Generated by Django 5.1.6 on 2025-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
