# Generated by Django 5.1.6 on 2025-03-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_api', '0002_item_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ranking_list',
            new_name='ranking_id',
        ),
    ]
