# Generated by Django 5.1.6 on 2025-03-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_api', '0003_rename_ranking_list_item_ranking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ranking_id',
            new_name='ranking',
        ),
    ]
